/* Playwright smoke test for the Page & Experience Manager.
   node pw-xm.js [path/to/haico-platform.html]
   1) every demo role × every static route: 0 page errors, 0 "Page not found"
   2) the administrator workflow: menu, submenu, page, section, component, rename, hide, move,
      font, terminology, save draft, review, publish, version, preview as employee (actions off),
      edit mode, compare, restore, import validation. Exits non-zero on any failure. */
const { chromium } = require(process.env.PW_MODULE || "/opt/node-tools/node_modules/playwright");
const fs = require("fs"), path = require("path");
const FILE = path.resolve(process.argv[2] || "haico-platform.html");
const SHOTS = path.resolve("shots-xm"); fs.mkdirSync(SHOTS, { recursive: true });
const fails = [];
const check = (ok, msg) => { if (!ok) { fails.push(msg); console.log("  FAIL", msg); } else console.log("  ok  ", msg); };
(async () => {
  const b = await chromium.launch(); const page = await b.newPage({ viewport: { width: 1360, height: 900 } });
  const errs = [];
  page.on("pageerror", (e) => errs.push(e.message));
  page.on("console", (m) => { if (m.type() === "error" && !/ERR_CERT|net::|fonts\.g/.test(m.text())) errs.push("console: " + m.text().slice(0, 200)); });
  page.on("dialog", (d) => d.dismiss());
  await page.goto("file://" + FILE); await page.waitForTimeout(1500);
  const pick = async () => { const g = await page.$("text=The whole group"); if (g) { await g.click(); await page.waitForTimeout(250); } };
  const login = async (l) => { const sw = await page.$(".banner button"); if (sw) { await sw.click(); await page.waitForTimeout(150); } await page.click(`.roles >> text="${l}"`); await page.waitForTimeout(400); await pick(); };
  const go = async (p) => { await page.evaluate((p) => go(p), p); await page.waitForTimeout(120); };
  const h1 = async () => (await page.locator(".content h1").first().textContent().catch(() => "")).trim();
  const shot = async (n) => { await page.waitForTimeout(450); await page.screenshot({ path: `${SHOTS}/${n}.png` }); };
  const text = async () => (await page.locator(".content").innerText().catch(() => ""));
  const modalText = async () => (await page.locator(".modal").innerText().catch(() => ""));
  const count = (sel) => page.locator(sel).count();
  const routes = await page.evaluate(() => ROUTES.map((r) => r.re.source).filter((s) => !s.includes("([^/]+)")).map((s) => s.replace(/^\^|\$$/g, "").replace(/\\\//g, "/")));
  console.log("1) every role × every static route (" + routes.length + ")");
  for (const r of ["Employee", "Manager", "HR Manager", "Finance Manager", "Executive Director", "Administrator"]) {
    await login(r); let nf = 0;
    for (const p of routes) { await go(p); nf += await count("text=Page not found"); }
    const items = await count(".side .item");
    check(nf === 0 && items > 0 && errs.length === 0, `${r}: ${items} menu items, ${nf} not-found, ${errs.length} errors ${errs.slice(0, 2).join(" | ")}`);
  }
  check(await page.evaluate(() => typeof window.xmWork === "function" && Object.keys(XM_COMPONENTS).length >= 40), "component library loaded (" + (await page.evaluate(() => Object.keys(XM_COMPONENTS).length)) + " components)");
  console.log("2) employee cannot open the manager; administrator can");
  await login("Employee"); await go("/admin/experience"); check((await text()).includes("Not available for your role"), "employee is denied /admin/experience");
  check(!(await page.locator(".side .item").allTextContents()).some((t) => /Administration/.test(t)), "employee has no Administration menu");
  await login("Administrator"); await go("/admin/experience"); check((await h1()).startsWith("Page & Experience"), "administrator opens the manager");
  check((await page.locator(".stabs").innerText()).includes("Page & Experience"), "manager is a tab of Administration");
  await page.evaluate(() => { localStorage.removeItem("haico-xm-work-v1"); XM.work = null; XM.scope = "default"; });
  for (const t of ["navigation", "pages", "library", "terminology", "typography", "views", "preview", "versions"]) { await go("/admin/experience/" + t); check(errs.length === 0 && !(await text()).includes("couldn't be drawn"), "tab " + t + " renders"); }
  await shot("admin-overview"); await go("/admin/experience/navigation"); await shot("admin-navigation");
  console.log("3) navigation: add menu, add submenu, rename, hide, reorder");
  await page.click('[data-a="xmMenuNew"]'); await page.waitForTimeout(150);
  await page.fill('.modal input[name="label"]', "Operations hub"); await page.check('.modal input[name="destType"][value="route"]'); await page.selectOption('.modal select[name="href"]', "/procurement/pos"); await page.selectOption('.modal select[name="group"]', "Operations"); await page.check('.modal input[name="aud"][value="finance"]');
  await page.click(".modal button.btn.pri"); await page.waitForTimeout(200);
  check((await text()).includes("Operations hub"), "custom menu added to the editor");
  await page.click('[data-a="xmSubmenuNew"]'); await page.waitForTimeout(150);
  await page.fill('.modal input[name="label"]', "Contracts"); await page.selectOption('.modal select[name="parent"]', "ops-projects"); await page.check('.modal input[name="destType"][value="new"]'); await page.fill('.modal input[name="newPage"]', "Contracts"); await page.click(".modal button.btn.pri"); await page.waitForTimeout(200);
  check(await page.evaluate(() => (xmWork().nav.custom || []).some((m) => m.kind === "submenu" && m.label === "Contracts") && !!xmWork().customPages.contracts), "custom submenu + new page created");
  await page.click('[data-a="xmItemEdit"][data-key="people"]'); await page.waitForTimeout(150); await page.fill('.modal input[name="label"]', "Our people"); await page.click(".modal button.btn.pri"); await page.waitForTimeout(200);
  check(await page.evaluate(() => xmWork().nav.items.people?.label === "Our people"), "menu renamed People → Our people");
  await page.click('[data-a="xmItemHide"][data-key="ops-sales"]'); await page.waitForTimeout(150);
  check(await page.evaluate(() => xmWork().nav.items["ops-sales"]?.hidden === true), "menu Sales & Stock hidden");
  await page.click('[data-a="xmItemMove"][data-key="fin-banking"][data-d="-1"]'); await page.waitForTimeout(150);
  check(await page.evaluate(() => (xmWork().nav.items["fin-banking"]?.order ?? 99) < (xmWork().nav.items["fin-ar"]?.order ?? 99)), "menu Banking moved above Accounts Receivable");
  await page.click('[data-a="tab"][data-k="xmnav-fin-ap"]'); await page.waitForTimeout(120);
  await page.click('[data-a="xmTabHide"][data-key="fin-ap"][data-href="/finance/ap/attachments"]'); await page.waitForTimeout(150);
  check(await page.evaluate(() => xmWork().nav.tabs["fin-ap|/finance/ap/attachments"]?.hidden === true), "submenu AP › Files hidden");
  console.log("4) pages: rename a section, hide a component, add a section and a Leave balance component to Home");
  await go("/admin/experience/pages/" + encodeURIComponent("/dashboard")); await shot("admin-page-home");
  const blocks = await page.evaluate(() => xmDiscover("/dashboard").blocks.map((b) => [b.key, b.comps.map((c) => c.key)]));
  check(blocks.length >= 4, "home structure discovered: " + blocks.map((b) => b[0]).join(", "));
  await page.evaluate(() => XM.scope = "role:employees");
  await page.click('[data-a="xmScope"]'); await page.waitForTimeout(100); await page.selectOption('select[name="scope"]', "role:employees"); await page.waitForTimeout(200);
  const empBlocks = await page.evaluate(() => xmDiscover("/dashboard").blocks);
  const qa = empBlocks.flatMap((b) => b.comps).find((c) => /quick-actions/.test(c.key)); const greet = empBlocks.find((b) => b.key === "greeting"); const coming = empBlocks.flatMap((b) => b.comps).find((c) => /coming-up/.test(c.key));
  check(!!qa && !!greet && !!coming, "employee home has greeting, quick actions, coming up (" + empBlocks.map((b) => b.key).join(", ") + ")");
  await page.click(`[data-a="xmBlockOp"][data-op="rename"][data-key="${qa.key}"]`); await page.waitForTimeout(150); await page.fill('.modal input[name="title"]', "Shortcuts"); await page.click(".modal button.btn.pri"); await page.waitForTimeout(150);
  await page.click(`[data-a="xmBlockOp"][data-op="hide"][data-key="${coming.key}"]`); await page.waitForTimeout(150);
  check(await page.evaluate((k) => xmWork().overrides["role:employees"].pages["/dashboard"].blocks[k]?.title === "Shortcuts", qa.key), "employee view: Quick actions renamed to Shortcuts");
  check(await page.evaluate((k) => xmWork().overrides["role:employees"].pages["/dashboard"].blocks[k]?.hidden === true, coming.key), "employee view: Coming up hidden");
  await page.click('[data-a="xmAddSection"]'); await page.waitForTimeout(150); await page.fill('.modal input[name="o_title"]', "Emergency contacts"); await page.selectOption('.modal select[name="where"]', "start"); await page.click(".modal button.btn.pri"); await page.waitForTimeout(150);
  await page.click('[data-a="xmAddComp"][data-where="end"]'); await page.waitForTimeout(150); await page.fill("#xmPickQ", "leave"); await page.waitForTimeout(100);
  check((await modalText()).includes("Leave Balance") && !(await modalText()).includes("AP Aging"), "library search 'leave' finds Leave Balance and not AP Aging");
  await page.click('[data-a="xmCompPick"][data-id="leave-balance"]'); await page.waitForTimeout(150);
  check((await modalText()).includes("Leave balance records"), "component preview shows purpose, data and permission");
  await page.selectOption('.modal select[name="where"]', "after"); await page.selectOption('.modal select[name="block"]', empBlocks[1]?.key || empBlocks[0].key); await page.selectOption('.modal select[name="size"]', "small"); await page.click(".modal button.btn.pri"); await page.waitForTimeout(200);
  check(await page.evaluate(() => { const p = xmWork().overrides["role:employees"].pages["/dashboard"]; return p.added.some((a) => a.kind === "section" && a.title === "Emergency contacts") && p.added.some((a) => a.component === "leave-balance"); }), "section + Leave balance added to Employee Home (employee view)");
  await page.evaluate(() => XM.scope = "default");
  console.log("5) typography + terminology");
  await go("/admin/experience/typography"); await page.selectOption('select[name="font"]', "inter"); await page.waitForTimeout(150); await page.selectOption('select[name="size"]', "15"); await page.waitForTimeout(150);
  check(await page.evaluate(() => xmWork().typography.font === "inter" && xmWork().typography.size === "15"), "font Inter, size 15px set");
  check((await page.locator(".xm-typo-prev").getAttribute("style")).includes("Inter"), "typography preview updates live");
  await go("/admin/experience/terminology"); await page.fill('input[name="t:employee-records"]', "People records"); await page.fill('input[name="t:request-time-off"]', "Request leave"); await page.click('form[data-f="xmTermsSave"] button.btn.pri'); await page.waitForTimeout(150);
  check(await page.evaluate(() => xmWork().labels["employee-records"] === "People records" && xmWork().labels["request-time-off"] === "Request leave"), "terms saved to the draft");
  console.log("6) save draft, review, publish");
  await go("/admin/experience/versions"); const unsaved = await page.evaluate(() => xmUnsaved().length); check(unsaved > 8, "unsaved changes counted: " + unsaved);
  await page.click('[data-a="xmSaveDraft"]'); await page.waitForTimeout(150); await page.fill('.modal input[name="note"]', "First configuration"); await page.click(".modal button.btn.pri"); await page.waitForTimeout(250);
  check(await page.evaluate(() => !!S.xmDraft && S.xmDraft.note === "First configuration" && xmUnsaved().length === 0), "draft saved as an audited event");
  await page.click('[data-a="xmReview"]'); await page.waitForTimeout(300); const review = await modalText();
  check(/Review changes/.test(review) && /Navigation/i.test(review) && /Employees:/.test(review) && /Typography/i.test(review), "review shows change list and roles affected"); await shot("admin-review");
  await page.fill("#xmPubNote", "Go live"); await page.click('form[data-f="xmPublish"] button.btn.pri'); await page.waitForTimeout(400);
  check(await page.evaluate(() => S.xmPublished?.version === 1 && S.xmVersions.length === 1 && S.xmVersions[0].changes.length > 8 && !S.xmDraft), "published as version 1 with a change list; draft cleared");
  check(await page.evaluate(() => S.audit.some((a) => a.module === "admin" && a.action === "POST" && /version 1/.test(a.summary))), "publish is in the audit log");
  await shot("admin-versions");
  console.log("7) the published configuration is live for everyone");
  await login("Finance Manager"); const navTxt = await page.locator(".side").innerText();
  check(navTxt.includes("Our people") && navTxt.includes("Operations hub") && !navTxt.includes("Sales & Stock"), "finance sees renamed menu, custom menu (finance-only), hidden menu gone");
  const sideItems = await page.locator(".side .item").allTextContents(); const iB = sideItems.findIndex((t) => /Banking/.test(t)), iAR = sideItems.findIndex((t) => /Accounts Receivable/.test(t)); check(iB >= 0 && iB < iAR, "Banking is above Accounts Receivable");
  await go("/finance/ap"); check(!(await page.locator(".stabs").innerText()).includes("Files"), "AP › Files submenu hidden");
  await page.click('.side .item:has-text("Operations hub")'); await page.waitForTimeout(200); check((await page.locator(".side .item.on").innerText()).includes("Operations hub") && (await h1()).includes("Purchase"), "custom menu opens its page and highlights");
  check((await page.evaluate(() => getComputedStyle(document.body).fontFamily)).includes("Inter"), "font Inter applied");
  check((await page.evaluate(() => getComputedStyle(document.querySelector(".content .wrap")).zoom)) !== "1", "base size 15px applied (zoom)");
  await go("/hr/employees"); check((await h1()) === "People records", "term applied: Employee records → People records");
  await login("Employee"); await go("/dashboard"); const empHome = await text();
  check(empHome.includes("Shortcuts") && !empHome.includes("Coming up") && empHome.includes("Emergency contacts") && empHome.includes("Leave balance") && empHome.includes("Request leave"), "employee home: renamed section, hidden card, added section, Leave balance with renamed button");
  check(!(await page.locator(".side").innerText()).includes("Operations hub"), "employee does not see the finance-only custom menu");
  await go("/pages/contracts"); check((await h1()) === "Contracts", "custom page opens at /pages/contracts");
  await go("/sales/orders"); check(!(await text()).includes("Page not found"), "hidden menu's page still obeys its own permission (route unchanged)");
  await shot("employee-home-configured");
  console.log("8) view as + edit mode + actions blocked");
  await login("Administrator"); await go("/admin/experience/preview"); await page.click('[data-a="xmViewAs"][data-id="u1"]'); await page.waitForTimeout(300);
  check((await page.locator(".xm-pv").innerText()).includes("VIEWING AS KIONA CARDINAL"), "preview banner names the person");
  check((await page.locator(".side .me").innerText()).includes("Kiona Cardinal"), "sidebar shows the previewed person");
  const blocked = await page.evaluate(() => { const before = S.audit.length; const ok = act("leave.withdraw", { requestId: "nope" }); return !ok && S.audit.length === before && SYNC.events.every((e) => e.type !== "leave.withdraw"); });
  check(blocked, "real actions are blocked in preview");
  await page.click('[data-a="xmEditMode"][data-v="1"]'); await page.waitForTimeout(300); await shot("preview-edit-mode");
  check((await count(".xm-tools")) > 3 && (await count(".xm-addbar")) === 1, "edit mode shows block controls and the add bar");
  await page.evaluate(() => XM.scope = "default");
  const firstRename = page.locator('.xm-tools [data-op="rename"]').first(); const key = await firstRename.getAttribute("data-key"); await firstRename.click(); await page.waitForTimeout(150); await page.fill('.modal input[name="title"]', "Hello there"); await page.click(".modal button.btn.pri"); await page.waitForTimeout(250);
  check(await page.evaluate((k) => xmWork().pages["/dashboard"].blocks[k]?.title === "Hello there", key), "renamed a block in place while previewing");
  await page.click('[data-a="xmExitPreview"]'); await page.waitForTimeout(250); check((await h1()).startsWith("Page & Experience") && !(await count(".xm-pv")), "exit preview returns to the manager");
  console.log("9) version 2, compare, restore, downloads, import validation");
  await go("/admin/experience/versions"); await page.click('[data-a="xmReview"]'); await page.waitForTimeout(250); await page.click('form[data-f="xmPublish"] button.btn.pri'); await page.waitForTimeout(400);
  check(await page.evaluate(() => S.xmPublished?.version === 2), "published version 2");
  await go("/admin/experience/versions?a=1&b=2"); const cmp = await text(); check(/Version 1 → Version 2/.test(cmp) && /Hello there/.test(cmp), "compare shows the difference");
  await page.click('[data-a="xmRestore"][data-v="1"]'); await page.waitForTimeout(150); check((await modalText()).includes("Restore the Page & Experience configuration from Version 1?"), "restore asks for confirmation");
  await page.click('[data-a="xmRestoreConfirm"]'); await page.waitForTimeout(400);
  check(await page.evaluate(() => S.xmPublished?.version === 3 && S.xmVersions[2].restoredFrom === 1 && JSON.stringify(S.xmVersions[2].config) === JSON.stringify(S.xmVersions[0].config)), "restored version 1 as version 3 (identical configuration)");
  check(await page.evaluate(() => S.employees.length === 18 && S.audit.some((a) => /restored/.test(a.summary))), "restore touched no data and is audited");
  const pkg = await page.evaluate(() => xmPackage(S.xmPublished.config, { version: 3, createdBy: "t", createdDate: "2026-10-02T00:00:00Z", publishedDate: "2026-10-02T00:00:00Z" }));
  const known = ["schema", "nav", "pages", "customPages", "labels", "customTerms", "typography", "density", "overrides"];
  const sensitive = /TEST26|@haico\.demo|accountNumber|EMP-\d{4}|grossCents|password|token/i.test(JSON.stringify(pkg));
  check(!sensitive && Object.keys(pkg.configuration).every((k) => known.includes(k)) && pkg.configurationSchema === 1 && pkg.erpVersion && pkg.organization, "export package carries schema/version/org and only UI configuration");
  check(await page.evaluate(() => { const r = xmValidateImport({ configurationSchema: 1, erpVersion: XM_ERP_VERSION, configuration: { nav: { items: { nonsense: { hidden: true } } }, pages: { "/nope": {} } } }); return r.errors.length >= 2 && !r.config; }), "import rejects unknown menus and pages");
  check(await page.evaluate(() => xmValidateImport({ configurationSchema: 9, configuration: {} }).errors.some((e) => /schema/.test(e))), "import rejects a wrong schema version");
  check(await page.evaluate((p) => { const r = xmValidateImport(p); return !r.errors.length && JSON.stringify(xmSanitize(r.config)) === JSON.stringify(xmSanitize(S.xmPublished.config)); }, pkg), "a round-tripped export validates and matches");
  check(await page.evaluate((p) => { XM.importPending = { pkg: p, fileName: "roundtrip.json" }; const ok = act("xm.import", { pkg: p, fileName: "roundtrip.json" }); return ok && S.xmDraft?.source === "import" && S.xmPublished.version === 3; }, pkg), "import creates a draft, never publishes");
  const pdf = await page.evaluate(() => { const rows = xmReportRows(S.xmPublished.config, { version: 3 }); const bytes = buildPdf(rows, "t", "s"); return [rows.length, bytes.length, String.fromCharCode(...bytes.slice(0, 5))]; });
  check(pdf[0] > 10 && pdf[2] === "%PDF-", "PDF report builds (" + pdf[0] + " rows, " + pdf[1] + " bytes)");
  const zip = await page.evaluate(() => { const z = xmZip([["a.json", "{}"], ["b.pdf", buildPdf([["A"]], "t", "")]]); return [z.length, z[0] === 0x50 && z[1] === 0x4b]; }); check(zip[1], "ZIP package builds (" + zip[0] + " bytes)");
  check(await page.evaluate(() => { const b = buildXlsx(EXPORTS["xm-history"]().rows, "History"); return b.length > 500; }), "change history export builds");
  console.log("10) every role × every route again with the configuration published");
  for (const r of ["Employee", "Manager", "HR Manager", "Finance Manager", "Executive Director", "Administrator"]) { await login(r); let nf = 0; for (const p of routes) { await go(p); nf += await count("text=Page not found"); } check(nf === 0, `${r}: ${nf} not-found with configuration live`); }
  check(errs.length === 0, "no page errors in the whole run" + (errs.length ? ": " + errs.slice(0, 5).join(" | ") : ""));
  await b.close();
  console.log(fails.length ? `\n${fails.length} FAILED` : "\nALL PASSED");
  process.exit(fails.length ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(2); });
