/* ==========================================================================
   views-xm-lib.js — Component & Widget Library for the Page & Experience Manager.
   Every component reads live ERP data through the same helpers the pages use and
   is gated by the same permissions. Nothing here posts, approves or edits data:
   actions and shortcuts open the existing workflows.
   ========================================================================== */

function xmAllowed(perm, a = A) {
  if (!perm || !a) return !perm;
  if (typeof perm === "function") { try { return !!perm(a); } catch { return false; } }
  return (Array.isArray(perm) ? perm : [perm]).some((p) => (p === "@employee" ? !!a.employee : can(a, p)));
}
const xmPermText = (perm) => (!perm ? "None (everyone)" : typeof perm === "function" ? "Decided by the page's own rules" : (Array.isArray(perm) ? perm : [perm]).map((p) => (p === "@employee" ? "an employee record" : p)).join(" or "));
function xmRangeDates(range) {
  const t = todayStr();
  if (range === "month") return [t.slice(0, 8) + "01", t];
  if (range === "quarter") { const m = +t.slice(5, 7); const qm = m - ((m - 1) % 3); return [`${t.slice(0, 5)}${String(qm).padStart(2, "0")}-01`, t]; }
  if (range === "year") return [t.slice(0, 5) + "01-01", t];
  if (range === "all") return ["0000-01-01", "9999-12-31"];
  return [addDays(t, -30), t];
}
const xmInRange = (d, r) => { if (!d) return false; const s = String(d).slice(0, 10); return s >= r[0] && s <= r[1]; };
/** the employees a scope covers, for the person looking */
function xmScopeEmps(scope, a = A) {
  const ids = scopeIds(S, a), me = a.employee;
  const emps = S.employees.filter((e) => ids.includes(e.companyId) && e.status !== "TERMINATED");
  switch (scope) {
    case "user": return me ? emps.filter((e) => e.id === me.id) : [];
    case "team": return me ? emps.filter((e) => e.managerId === me.id || e.id === me.id) : [];
    case "department": return me ? emps.filter((e) => e.departmentId === me.departmentId) : [];
    case "company": { const c = a.activeCompanyId || me?.companyId; return c ? emps.filter((e) => e.companyId === c) : emps; }
    default: return emps;
  }
}
const xmScopeText = (scope) => XM_SCOPES.find((s) => s[0] === scope)?.[1] || "Organization";
const xmCard = (title, body, right = "", cls = "") => `<section class="hcard ${cls}">${title ? `<div class="hcard-h"><h2>${esc(title)}</h2>${right}</div>` : ""}${body}</section>`;
const xmLink = (go, label) => `<button class="lnk" style="font-size:12.5px" data-go="${esc(go)}">${esc(label)}</button>`;
const xmEmptyMsg = (t) => `<p class="xm-empty">${esc(t)}</p>`;
const xmList = (rows) => (rows.length ? `<ul class="xm-list">${rows.map((r) => `<li><span style="min-width:0"><b>${esc(r.t)}</b>${r.s ? `<small>${esc(r.s)}</small>` : ""}</span>${r.r != null ? `<span class="num" style="white-space:nowrap">${esc(r.r)}</span>` : ""}</li>`).join("")}</ul>` : "");
const xmTiles = (tiles) => `<div class="xm-tiles">${tiles.map((t) => `<button class="stat" ${t.go ? `data-go="${esc(t.go)}"` : ""} style="text-align:left;font:inherit;cursor:${t.go ? "pointer" : "default"}"><div class="l">${esc(t.l)}</div><div class="v">${esc(t.v)}</div>${t.h ? `<div class="h hint">${esc(t.h)}</div>` : ""}</button>`).join("")}</div>`;
const xmBars = (items, fmt = (v) => String(v)) => { const max = Math.max(1, ...items.map((x) => x.v)); return items.length ? `<div class="xm-bars">${items.map((x, i) => `<div class="hbar"><span class="nm" title="${esc(x.label)}">${esc(x.label)}</span><span class="tr"><i style="width:${Math.round((x.v / max) * 100)}%;background:var(--c${(i % 6) + 1})"></i></span><span class="num" style="font-size:12px;min-width:64px;text-align:right">${esc(x.d || fmt(x.v))}</span></div>`).join("")}</div>` : xmEmptyMsg("Nothing to chart for this selection."); };
function xmLineSvg(labels, lines, fmt = (v) => String(v)) {
  const W = 520, H = 170, L = 44, R = 10, T = 12, B = 26;
  const all = lines.flatMap((l) => l.values); const max = Math.max(1, ...all), min = Math.min(0, ...all);
  const x = (i) => L + (i * (W - L - R)) / Math.max(1, labels.length - 1), y = (v) => T + (H - T - B) * (1 - (v - min) / (max - min || 1));
  const grid = [0, 0.5, 1].map((f) => { const v = min + (max - min) * f; return `<line x1="${L}" x2="${W - R}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}" stroke="var(--grid)" stroke-dasharray="3 3"/><text class="ax" x="${L - 4}" y="${(y(v) + 3).toFixed(1)}" text-anchor="end">${esc(fmt(v))}</text>`; }).join("");
  const paths = lines.map((l, li) => `<path class="${li ? "l2" : "l"}" d="${l.values.map((v, i) => `${i ? "L" : "M"}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(" ")}"/>${l.values.map((v, i) => `<circle class="dot" cx="${x(i).toFixed(1)}" cy="${y(v).toFixed(1)}" r="2.5" style="fill:var(--c${li + 1})"><title>${esc(labels[i])}: ${esc(fmt(v))}</title></circle>`).join("")}`).join("");
  const ax = labels.map((lb, i) => (labels.length > 8 && i % 2 ? "" : `<text class="ax" x="${x(i).toFixed(1)}" y="${H - 8}" text-anchor="middle">${esc(lb)}</text>`)).join("");
  const legend = lines.length > 1 ? `<div class="form-row" style="gap:14px;padding:0 4px 6px;font-size:12px">${lines.map((l, i) => `<span class="chip"><span class="sq" style="background:var(--c${i + 1})"></span>${esc(l.name)}</span>`).join("")}</div>` : "";
  return `<div class="xm-line"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Trend">${grid}${paths}${ax}</svg>${legend}</div>`;
}
const xmMonths = (n) => { const out = []; const t = todayStr(); let y = +t.slice(0, 4), m = +t.slice(5, 7); for (let i = 0; i < n; i++) { out.unshift(`${y}-${String(m).padStart(2, "0")}`); m--; if (!m) { m = 12; y--; } } return out; };
const xmNetOpen = (list) => list.reduce((t, i) => t + (i.totalCents || 0) - (i.paidCents || 0), 0);
const xmOpenBills = (a = A) => inScope(S.apInvoices).filter((i) => ["APPROVED", "PARTIALLY_PAID", "PENDING_APPROVAL"].includes(i.status));
const xmOpenInvoices = () => inScope(S.arInvoices).filter((i) => ["SENT", "APPROVED", "PARTIALLY_PAID"].includes(i.status));
function xmAging(list) {
  const t = todayStr(), b = [["Current", 0], ["1–30 days", 0], ["31–60 days", 0], ["61–90 days", 0], ["Over 90", 0]];
  for (const i of list) { const open = (i.totalCents || 0) - (i.paidCents || 0); if (open <= 0) continue; const days = Math.round((D(t) - D(i.dueDate)) / MS_DAY); const k = days <= 0 ? 0 : days <= 30 ? 1 : days <= 60 ? 2 : days <= 90 ? 3 : 4; b[k][1] += open; }
  return b.map(([label, v]) => ({ label, v, d: moneyCompact(v) }));
}
const xmAcct = (id) => byId(S.accounts, id);
function xmExpenseByAccount(range, ids) {
  const r = xmRangeDates(range), m = new Map();
  const jeOk = new Map(S.journalEntries.filter((j) => ids.includes(j.companyId) && j.status !== "VOID" && xmInRange(j.date, r)).map((j) => [j.id, j]));
  for (const l of S.journalLines) { if (!jeOk.has(l.journalEntryId)) continue; const a = xmAcct(l.accountId); if (!a || a.type !== "EXPENSE") continue; m.set(a.name, (m.get(a.name) || 0) + (l.debitCents || 0) - (l.creditCents || 0)); }
  return [...m].filter(([, v]) => v > 0).sort((x, y) => y[1] - x[1]).slice(0, 8).map(([label, v]) => ({ label, v, d: moneyCompact(v) }));
}
function xmMonthlyPL(ids, months) {
  const rev = Object.fromEntries(months.map((m) => [m, 0])), exp = { ...rev };
  const je = new Map(S.journalEntries.filter((j) => ids.includes(j.companyId) && j.status !== "VOID").map((j) => [j.id, j]));
  for (const l of S.journalLines) { const j = je.get(l.journalEntryId); if (!j) continue; const m = j.date.slice(0, 7); if (!(m in rev)) continue; const a = xmAcct(l.accountId); if (!a) continue; if (a.type === "REVENUE") rev[m] += (l.creditCents || 0) - (l.debitCents || 0); else if (a.type === "EXPENSE") exp[m] += (l.debitCents || 0) - (l.creditCents || 0); }
  return { labels: months.map((m) => MON[+m.slice(5, 7) - 1]), lines: [{ name: "Revenue", values: months.map((m) => Math.round(rev[m] / 100)) }, { name: "Expenses", values: months.map((m) => Math.round(exp[m] / 100)) }] };
}
const xmCurrentPeriod = (e) => { const st = settingsFor(S, e.companyId), cad = st.timesheetCadence || "BIWEEKLY", start = periodStartFor(todayStr(), cad); return { start, end: periodEndFor(start, cad), cad }; };
const xmStatusWord = (s) => (STATUS[s] || [s])[0];

/* ---- approved quick actions: every one opens an existing page or workflow ---- */
const XM_ACTIONS_LIB = [
  { id: "enter-time", label: "Enter my hours", icon: "clock", go: "/me/time", perm: "@employee" },
  { id: "request-time-off", label: "Request time off", icon: "calendar", go: "/me/time-off", perm: "@employee" },
  { id: "submit-expense", label: "Submit an expense", icon: "receipt", go: "/me/expenses", perm: "@employee" },
  { id: "new-request", label: "New request", icon: "plus", go: "/me/requests", perm: "@employee" },
  { id: "view-pay", label: "View my pay", icon: "wallet", go: "/me/pay", perm: "@employee" },
  { id: "my-documents", label: "My documents", icon: "folder", go: "/me/documents", perm: "@employee" },
  { id: "my-tasks", label: "My tasks", icon: "tasks", go: "/me/tasks", perm: "@employee" },
  { id: "directory", label: "Find a colleague", icon: "directory", go: "/people/directory", perm: ["@employee", "hr.employees.view"] },
  { id: "approvals", label: "Open approvals", icon: "check", go: "/approvals", perm: (a) => myActionable().length > 0 || myTimesheetsToApprove().length > 0 || ["timesheets.approve", "leave.approve", "expenses.approve", "ap.approve", "payroll.approve", "procurement.approve"].some((p) => can(a, p)) },
  { id: "approve-timesheets", label: "Approve timesheets", icon: "clock", go: "/approvals?tab=timesheets", perm: "timesheets.approve" },
  { id: "approve-leave", label: "Approve time off", icon: "calendar", go: "/approvals?tab=timeoff", perm: "leave.approve" },
  { id: "approve-expenses", label: "Approve expenses", icon: "receipt", go: "/approvals?tab=expenses", perm: "expenses.approve" },
  { id: "team", label: "My team", icon: "users", go: "/team", perm: (a) => teamLeads() },
  { id: "new-bill", label: "Enter a bill", icon: "filetext", act: "newBill", go: "/finance/ap", perm: "ap.create" },
  { id: "bills-batch", label: "Enter bills in a batch", icon: "sheet", go: "/finance/ap/batch", perm: "ap.create" },
  { id: "pay-bills", label: "Record payments", icon: "banknote", go: "/finance/ap/pay", perm: "ap.pay" },
  { id: "new-invoice", label: "Create an invoice", icon: "filetext", act: "newInvoice", go: "/finance/ar", perm: "ar.create" },
  { id: "deposit", label: "Record a deposit", icon: "piggybank", go: "/finance/ar/deposit", perm: "ar.receive" },
  { id: "new-journal", label: "Post a journal entry", icon: "book", go: "/finance/journals/new", perm: "finance.post" },
  { id: "banking", label: "Match the bank", icon: "piggybank", go: "/finance/banking", perm: "banking.view" },
  { id: "month-end", label: "Month-end close", icon: "calendarlock", go: "/finance/periods", perm: "finance.periods" },
  { id: "new-employee", label: "Add an employee", icon: "user", go: "/hr/employees/new", perm: "hr.employees.create" },
  { id: "new-opening", label: "Open a job posting", icon: "briefcase", go: "/hr/hiring/new", perm: "hr.employees.edit" },
  { id: "hr-timesheets", label: "Everyone's timesheets", icon: "clock", go: "/hr/timesheets", perm: "timesheets.view" },
  { id: "hr-leave", label: "Everyone's time off", icon: "calendar", go: "/hr/leave", perm: "leave.view" },
  { id: "pay-run", label: "Pay runs", icon: "banknote", go: "/payroll/runs", perm: "payroll.view" },
  { id: "purchase-request", label: "Ask to buy something", icon: "cart", go: "/procurement/requests", perm: "procurement.create" },
  { id: "purchase-orders", label: "Purchase orders", icon: "cart", go: "/procurement/pos", perm: "procurement.view" },
  { id: "projects", label: "Projects", icon: "briefcase", go: "/projects", perm: "projects.view" },
  { id: "reports", label: "Reports", icon: "chart", go: "/reports", perm: (a) => can(a, "reports.view") || can(a, "finance.view") || can(a, "hr.employees.view") },
];
const XM_ACTION_BY_ID = Object.fromEntries(XM_ACTIONS_LIB.map((a) => [a.id, a]));
const xmActionBtn = (x) => `<button ${x.act ? `data-a="${esc(x.act)}"` : `data-go="${esc(x.go)}"`}>${icon(x.icon)}<span>${esc(x.label)}</span></button>`;

/* ---- approved metrics (KPI values are always computed from ERP data) ---- */
const XM_METRICS = {
  "outstanding-ap": { name: "Outstanding AP", perm: "ap.view", value: () => ({ v: moneyCompact(xmNetOpen(xmOpenBills())), h: "Unpaid vendor bills", go: "/finance/ap" }) },
  "outstanding-ar": { name: "Outstanding AR", perm: "ar.view", value: () => ({ v: moneyCompact(xmNetOpen(xmOpenInvoices())), h: "Unpaid customer invoices", go: "/finance/ar" }) },
  "overdue-ar": { name: "Overdue receivables", perm: "ar.view", value: () => { const t = todayStr(); return { v: moneyCompact(xmNetOpen(xmOpenInvoices().filter((i) => i.dueDate < t))), h: "Past due", go: "/finance/ar" }; } },
  "bills-due-30": { name: "Bills due in 30 days", perm: "ap.view", value: () => { const end = addDays(todayStr(), 30); const l = xmOpenBills().filter((i) => i.dueDate <= end); return { v: moneyCompact(xmNetOpen(l)), h: `${l.length} bill${l.length === 1 ? "" : "s"}`, go: "/finance/ap" }; } },
  "cash": { name: "Cash on hand", perm: "finance.view", value: () => ({ v: moneyCompact(cashOf(scopeIds(S, A))), h: "Bank, all posted activity", go: "/finance/banking" }) },
  "employees": { name: "Employees", perm: ["hr.employees.view", "@employee"], value: () => { const n = xmScopeEmps("organization").filter((e) => ["ACTIVE", "ON_LEAVE", "ONBOARDING"].includes(e.status)).length; return { v: String(n), h: "Active, on leave or starting", go: can(A, "hr.employees.view") ? "/hr/employees" : "/people/directory" }; } },
  "pending-approvals": { name: "Pending approvals (mine)", perm: null, value: () => { const n = myActionable().length + myTimesheetsToApprove().length; return { v: String(n), h: "Waiting for your decision", go: "/approvals" }; } },
  "timesheets-waiting": { name: "Timesheets waiting", perm: "timesheets.view", value: () => ({ v: String(inScope(S.timesheets).filter((t) => t.status === "SUBMITTED").length), h: "Sent, not yet approved", go: "/hr/timesheets" }) },
  "leave-waiting": { name: "Time off waiting", perm: "leave.view", value: () => ({ v: String(S.leaveRequests.filter((r) => r.status === "PENDING_APPROVAL" && scopeIds(S, A).includes(r.companyId)).length), h: "Requests not yet decided", go: "/hr/leave" }) },
  "my-leave-available": { name: "My vacation available", perm: "@employee", value: () => { const b = leaveBalances(A.employee.id).find((x) => x.lt.code === "VACATION" || /vacation/i.test(x.lt.name)); return { v: b ? `${hrs(b.avail)} h` : "—", h: b ? `${hrs(b.used)} h used this year` : "No balance on file", go: "/me/time-off" }; } },
  "my-timesheet": { name: "My timesheet", perm: "@employee", value: () => { const e = A.employee, p = xmCurrentPeriod(e); const s = S.timesheets.find((t) => t.employeeId === e.id && t.periodStart === p.start); return { v: s ? xmStatusWord(s.status) : "Not started", h: periodLabel(p.start, p.end), go: "/me/time" }; } },
  "open-tasks": { name: "Open tasks", perm: "@employee", value: () => { const l = (S.tasks || []).filter((t) => t.assigneeId === A.employee.id && t.status !== "DONE"); return { v: String(l.length), h: `${l.filter((t) => t.dueDate && t.dueDate < todayStr()).length} overdue`, go: "/me/tasks" }; } },
  "team-tasks-late": { name: "Team tasks late or blocked", perm: (a) => teamLeads(), value: () => ({ v: String(typeof teamTasksLate === "function" ? teamTasksLate() : 0), h: "Across your team", go: "/team" }) },
  "payroll-last": { name: "Last payroll", perm: "payroll.view", value: () => { const r = inScope(S.payrollRuns).filter((x) => x.status === "POSTED").sort((a, b) => (a.payDate < b.payDate ? 1 : -1))[0]; return { v: r ? moneyCompact(r.grossCents) : "—", h: r ? `Gross · paid ${dLong(r.payDate)}` : "None posted yet", go: "/payroll/runs" }; } },
  "open-pos": { name: "Open purchase orders", perm: "procurement.view", value: () => { const l = inScope(S.purchaseOrders || []).filter((p) => ["SENT", "APPROVED", "PARTIAL"].includes(p.status)); return { v: String(l.length), h: moneyCompact(l.reduce((s, p) => s + (p.totalCents || p.amountCents || 0), 0)), go: "/procurement/pos" }; } },
  "low-stock": { name: "Items at reorder point", perm: ["ar.view", "procurement.view"], value: () => { const ids = scopeIds(S, A); const n = (S.items || []).filter((it) => ids.includes(it.companyId) && it.isActive !== false && (S.stockLevels || []).filter((s) => s.itemId === it.id).reduce((t, s) => t + (s.onHand || 0), 0) <= (it.reorderPoint || 0)).length; return { v: String(n), h: "At or below the reorder point", go: "/inventory/stock" }; } },
  "expiring-certs": { name: "Certificates expiring", perm: "hr.employees.view", value: () => ({ v: String(typeof hr2ExpiringCerts === "function" ? hr2ExpiringCerts(60).length : 0), h: "Within 60 days", go: "/hr/certifications" }) },
  "onboarding": { name: "Starting soon", perm: "hr.employees.view", value: () => ({ v: String(inScope(S.employees).filter((e) => e.status === "ONBOARDING").length), h: "In onboarding", go: "/hr/onboarding" }) },
  "projects-active": { name: "Active projects", perm: "projects.view", value: () => ({ v: String(inScope(S.projects).filter((p) => p.status === "ACTIVE").length), h: "In progress", go: "/projects" }) },
  "expenses-open": { name: "Expense claims open", perm: "expenses.view", value: () => { const l = inScope(S.expenseClaims).filter((c) => ["SUBMITTED", "PENDING_APPROVAL", "APPROVED"].includes(c.status)); return { v: String(l.length), h: moneyCompact(l.reduce((s, c) => s + (c.totalCents || 0), 0)), go: "/finance/expenses" }; } },
};
/* ---- approved datasets for tables and lists ---- */
const XM_DATASETS = {
  "pending-approvals": { name: "Pending approvals", perm: null, cols: [["kind", "Request"], ["label", "What"], ["who", "Employee"], ["date", "Date", "date"], ["amount", "Amount", "money"], ["status", "Status", "badge"]], rows: () => myActionable().map((a) => ({ kind: TYPE_LABEL[a.entityType] || a.entityType, label: a.entityLabel, who: byId(S.users, a.requestedById)?.displayName || "", date: a.createdAt, amount: a.amountCents || null, status: a.status, go: "/approvals" })), link: ["/approvals", "Open approvals →"] },
  "my-requests": { name: "My requests & expenses", perm: "@employee", cols: [["kind", "Kind"], ["title", "Request"], ["date", "Date", "date"], ["amount", "Amount", "money"], ["status", "Status", "badge"]], rows: () => statusRows(A.employee.id).map((r) => ({ kind: r.kind, title: `${r.number ? r.number + " · " : ""}${r.title}`, date: r.at, amount: r.amount, status: r.status, go: r.href || "/me/requests" })), link: ["/me/requests", "All of them →"] },
  "leave-requests": { name: "Time-off requests", perm: ["leave.view", "@employee"], scoped: true, cols: [["who", "Employee"], ["type", "Type"], ["dates", "Dates"], ["hours", "Hours", "hours"], ["status", "Status", "badge"]], rows: (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); const r = xmRangeDates(c.range); return S.leaveRequests.filter((x) => emps.has(x.employeeId) && (can(A, "leave.view") || x.employeeId === A.employee?.id) && (c.range === "all" || xmInRange(x.startDate, r) || x.status === "PENDING_APPROVAL")).map((x) => ({ who: empName(byId(S.employees, x.employeeId)), type: byId(S.leaveTypes, x.leaveTypeId)?.name || "", dates: `${dShort(x.startDate)}${x.endDate !== x.startDate ? " → " + dShort(x.endDate) : ""}`, hours: x.totalHours, status: x.status, date: x.startDate })); }, link: ["/hr/leave", "Time off →"] },
  "timesheets": { name: "Timesheets", perm: ["timesheets.view", "@employee"], scoped: true, cols: [["who", "Employee"], ["period", "Pay period"], ["worked", "Worked", "hours"], ["status", "Status", "badge"]], rows: (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); return S.timesheets.filter((t) => emps.has(t.employeeId) && (can(A, "timesheets.view") || t.employeeId === A.employee?.id)).map((t) => ({ who: empName(byId(S.employees, t.employeeId)), period: periodLabel(t.periodStart, t.periodEnd), worked: t.workedHours, status: t.status, date: t.periodStart, go: can(A, "timesheets.view") ? `/hr/timesheets/${t.id}` : "/me/time" })); }, link: ["/hr/timesheets", "Timesheets →"] },
  "employees": { name: "Employees", perm: ["hr.employees.view", "@employee"], scoped: true, cols: [["name", "Name"], ["company", "Company"], ["department", "Department"], ["position", "Position"], ["started", "Started", "date"], ["status", "Status", "badge"]], rows: (c) => xmScopeEmps(c.scope).map((e) => ({ name: empName(e), company: co(e.companyId)?.displayName || "", department: byId(S.departments, e.departmentId)?.name || "", position: byId(S.positions, e.positionId)?.title || "", started: e.startDate, status: e.status, date: e.startDate, go: can(A, "hr.employees.view") ? `/hr/employees/${e.id}` : "/people/directory" })), link: ["/people/directory", "Directory →"] },
  "tasks": { name: "Tasks", perm: "@employee", scoped: true, cols: [["title", "Task"], ["who", "Assigned to"], ["due", "Due", "date"], ["pct", "Done", "pct"], ["status", "Status", "badge"]], rows: (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); return (S.tasks || []).filter((t) => emps.has(t.assigneeId) && (t.assigneeId === A.employee?.id || teamLeads()) && t.status !== "DONE").map((t) => ({ title: t.title, who: empName(byId(S.employees, t.assigneeId)), due: t.dueDate, pct: t.percentDone || 0, status: t.status, date: t.dueDate || "9999", go: `/team/${t.id}` })); }, link: ["/me/tasks", "My tasks →"] },
  "open-bills": { name: "Open vendor bills", perm: "ap.view", cols: [["vendor", "Vendor"], ["number", "Invoice"], ["due", "Due", "date"], ["open", "Open", "money"], ["status", "Status", "badge"]], rows: () => xmOpenBills().map((i) => ({ vendor: byId(S.vendors, i.vendorId)?.name || "", number: i.invoiceNumber, due: i.dueDate, open: (i.totalCents || 0) - (i.paidCents || 0), status: i.status, date: i.dueDate, go: `/finance/ap/${i.id}` })), link: ["/finance/ap", "Bills →"] },
  "customer-invoices": { name: "Open customer invoices", perm: "ar.view", cols: [["customer", "Customer"], ["number", "Invoice"], ["due", "Due", "date"], ["open", "Open", "money"], ["status", "Status", "badge"]], rows: () => xmOpenInvoices().map((i) => ({ customer: byId(S.customers, i.customerId)?.name || "", number: i.invoiceNumber, due: i.dueDate, open: (i.totalCents || 0) - (i.paidCents || 0), status: i.status, date: i.dueDate, go: "/finance/ar" })), link: ["/finance/ar", "Invoices →"] },
  "purchase-orders": { name: "Purchase orders", perm: "procurement.view", cols: [["number", "PO"], ["vendor", "Supplier"], ["what", "What"], ["amount", "Amount", "money"], ["status", "Status", "badge"]], rows: () => inScope(S.purchaseOrders || []).map((p) => ({ number: p.poNumber, vendor: p.vendorName || byId(S.vendors, p.vendorId)?.name || "", what: p.description || "", amount: p.totalCents || p.amountCents || 0, status: p.status, date: p.orderDate || p.createdAt, go: "/procurement/pos" })), link: ["/procurement/pos", "Purchase orders →"] },
  "expense-claims": { name: "Expense claims", perm: ["expenses.view", "@employee"], scoped: true, cols: [["who", "Employee"], ["number", "Claim"], ["purpose", "Purpose"], ["amount", "Amount", "money"], ["status", "Status", "badge"]], rows: (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); return inScope(S.expenseClaims).filter((x) => emps.has(x.employeeId) && (can(A, "expenses.view") || x.employeeId === A.employee?.id)).map((x) => ({ who: empName(byId(S.employees, x.employeeId)), number: x.claimNumber, purpose: x.purpose, amount: x.totalCents, status: x.status, date: x.createdAt })); }, link: ["/finance/expenses", "Claims →"] },
  "payroll-runs": { name: "Pay runs", perm: "payroll.view", cols: [["number", "Run"], ["period", "Pay period"], ["payDate", "Pay day", "date"], ["people", "People", "num"], ["gross", "Gross", "money"], ["status", "Status", "badge"]], rows: () => inScope(S.payrollRuns).map((r) => ({ number: r.runNumber, period: periodLabel(r.periodStart, r.periodEnd), payDate: r.payDate, people: r.employeeCount, gross: r.grossCents, status: r.status, date: r.payDate, go: `/payroll/runs/${r.id}` })), link: ["/payroll/runs", "Pay runs →"] },
  "projects": { name: "Projects", perm: "projects.view", cols: [["code", "Code"], ["name", "Project"], ["lead", "Led by"], ["budget", "Budget", "money"], ["status", "Status", "badge"]], rows: () => inScope(S.projects).map((p) => ({ code: p.code, name: p.name, lead: empName(byId(S.employees, p.managerId)), budget: p.budgetCents, status: p.status, date: p.startDate, go: `/projects/${p.id}` })), link: ["/projects", "Projects →"] },
  "vendors": { name: "Vendors", perm: "ap.view", cols: [["number", "No."], ["name", "Vendor"], ["company", "Company"], ["terms", "Terms", "num"], ["status", "Status", "badge"]], rows: () => inScope(S.vendors).map((v) => ({ number: v.vendorNumber, name: v.name, company: co(v.companyId)?.displayName || "", terms: v.paymentTermsDays, status: v.status, date: "", go: `/finance/ap/vendors/${v.id}` })), link: ["/finance/ap/vendors", "Vendors →"] },
  "customers": { name: "Customers", perm: "ar.view", cols: [["number", "No."], ["name", "Customer"], ["company", "Company"], ["terms", "Terms", "num"], ["status", "Status", "badge"]], rows: () => inScope(S.customers).map((c) => ({ number: c.customerNumber, name: c.name, company: co(c.companyId)?.displayName || "", terms: c.paymentTermsDays, status: c.status, date: "", go: "/finance/ar" })), link: ["/finance/ar", "Receivables →"] },
  "certifications": { name: "Certificates expiring", perm: ["hr.employees.view", "@employee"], scoped: true, cols: [["who", "Employee"], ["name", "Certificate"], ["expires", "Expires", "date"], ["days", "Days left", "num"]], rows: (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); const t = todayStr(); return (S.certifications || []).filter((x) => emps.has(x.employeeId) && (can(A, "hr.employees.view") || x.employeeId === A.employee?.id) && x.expiryDate).map((x) => ({ who: empName(byId(S.employees, x.employeeId)), name: x.name, expires: x.expiryDate, days: Math.round((D(x.expiryDate) - D(t)) / MS_DAY), date: x.expiryDate })).filter((x) => x.days <= 120); }, link: ["/hr/certifications", "Certificates →"] },
  "job-postings": { name: "Job openings", perm: "hr.employees.view", cols: [["title", "Opening"], ["company", "Company"], ["dept", "Department"], ["openings", "Openings", "num"], ["status", "Status", "badge"]], rows: () => inScope(S.jobPostings || []).map((j) => ({ title: j.title, company: co(j.companyId)?.displayName || "", dept: byId(S.departments, j.departmentId)?.name || "", openings: j.openings, status: j.status, date: j.postedAt || "", go: `/hr/hiring/${j.id}` })), link: ["/hr/hiring", "Hiring →"] },
  "upcoming-events": { name: "Upcoming events", perm: null, cols: [["when", "When", "date"], ["what", "Event"], ["kind", "Kind"]], rows: (c) => upcomingEventsA(c.days || 60).map((x) => ({ when: x.at, what: x.t, kind: EVENT_K[x.k]?.[0] || x.k, date: x.at })), link: ["/me/profile/events", "Calendar →"] },
  "recent-activity": { name: "Recent activity", perm: null, scoped: true, cols: [["when", "When", "datetime"], ["who", "By"], ["what", "What happened"]], rows: (c) => historyRowsA({ scope: c.scope === "user" ? "me" : c.scope === "team" ? "team" : (can(A, "audit.view") || can(A, "reports.view") || can(A, "hr.employees.view") || can(A, "finance.view")) ? "all" : "me" }).rows.map((r) => ({ when: r.at, who: r.actorName, what: r.summary, date: r.at })), link: ["/history", "All history →"] },
  "documents": { name: "Documents", perm: ["documents.view", "@employee"], cols: [["title", "Title"], ["category", "Category"], ["file", "File"], ["size", "Size", "num"]], rows: () => S.documents.filter((d) => d.visibility !== "HR_ONLY" || can(A, "hr.employees.view")).map((d) => ({ title: d.title, category: d.category, file: d.fileName, size: Math.round((d.sizeBytes || 0) / 1024), date: d.createdAt || "", go: "/documents" })), link: ["/me/documents", "Documents →"] },
};
/* ---- approved chart series ---- */
const XM_SERIES = {
  "headcount-department": { name: "Headcount by department", perm: ["hr.employees.view", "@employee"], kind: "cat", items: (c) => groupBars(xmScopeEmps(c.scope === "user" || c.scope === "team" ? "organization" : c.scope).filter((e) => e.status !== "TERMINATED"), (e) => byId(S.departments, e.departmentId)?.name || "—", () => 1, (v) => String(v)) },
  "headcount-company": { name: "Headcount by company", perm: ["hr.employees.view", "@employee"], kind: "cat", items: () => groupBars(xmScopeEmps("organization"), (e) => co(e.companyId)?.displayName || "—", () => 1, (v) => String(v)) },
  "expenses-account": { name: "Expenses by account", perm: "finance.view", kind: "cat", items: (c) => xmExpenseByAccount(c.range === "current" ? "year" : c.range, scopeIds(S, A)) },
  "ap-aging": { name: "AP aging", perm: "ap.view", kind: "cat", items: () => xmAging(xmOpenBills()) },
  "ar-aging": { name: "AR aging", perm: "ar.view", kind: "cat", items: () => xmAging(xmOpenInvoices()) },
  "ap-vendor": { name: "Open bills by vendor", perm: "ap.view", kind: "cat", items: () => groupBars(xmOpenBills(), (i) => byId(S.vendors, i.vendorId)?.name || "—", (i) => (i.totalCents || 0) - (i.paidCents || 0), moneyCompact) },
  "leave-type": { name: "Leave usage by type", perm: ["leave.view", "@employee"], kind: "cat", items: (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); return groupBars(S.leaveRequests.filter((r) => emps.has(r.employeeId) && r.status === "APPROVED" && (can(A, "leave.view") || r.employeeId === A.employee?.id)), (r) => byId(S.leaveTypes, r.leaveTypeId)?.name || "—", (r) => r.totalHours || 0, (v) => `${hrs(v)} h`); } },
  "hours-department": { name: "Hours by department", perm: ["timesheets.view", "@employee"], kind: "cat", items: (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); const ts = new Map(S.timesheets.filter((t) => emps.has(t.employeeId) && (can(A, "timesheets.view") || t.employeeId === A.employee?.id)).map((t) => [t.id, t])); return groupBars(S.timesheetEntries.filter((x) => ts.has(x.timesheetId)), (x) => byId(S.departments, x.departmentId)?.name || "—", (x) => x.workedHours || 0, (v) => `${hrs(v)} h`); } },
  "bills-status": { name: "Bills by status", perm: "ap.view", kind: "cat", items: () => groupBars(inScope(S.apInvoices), (i) => xmStatusWord(i.status), () => 1, (v) => String(v)) },
  "tasks-status": { name: "Tasks by status", perm: "@employee", kind: "cat", items: (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); return groupBars((S.tasks || []).filter((t) => emps.has(t.assigneeId) && (t.assigneeId === A.employee?.id || teamLeads())), (t) => (typeof TEAM_ST_LABEL !== "undefined" && TEAM_ST_LABEL[t.status]) || xmStatusWord(t.status), () => 1, (v) => String(v)); } },
  "revenue-expenses": { name: "Revenue and expenses by month", perm: "finance.view", kind: "time", series: () => xmMonthlyPL(scopeIds(S, A), xmMonths(6)), fmt: (v) => moneyCompact(v * 100) },
  "hours-period": { name: "Hours by pay period", perm: ["timesheets.view", "@employee"], kind: "time", series: (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); const m = new Map(); for (const t of S.timesheets) if (emps.has(t.employeeId) && (can(A, "timesheets.view") || t.employeeId === A.employee?.id)) m.set(t.periodStart, (m.get(t.periodStart) || 0) + (t.workedHours || 0)); const keys = [...m.keys()].sort().slice(-8); return { labels: keys.map(dShort), lines: [{ name: "Worked hours", values: keys.map((k) => Math.round(m.get(k) * 10) / 10) }] }; }, fmt: (v) => `${v} h` },
  "leave-month": { name: "Time off by month", perm: ["leave.view", "@employee"], kind: "time", series: (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); const months = xmMonths(6), m = Object.fromEntries(months.map((x) => [x, 0])); for (const r of S.leaveRequests) if (emps.has(r.employeeId) && r.status === "APPROVED" && (can(A, "leave.view") || r.employeeId === A.employee?.id) && r.startDate.slice(0, 7) in m) m[r.startDate.slice(0, 7)] += r.totalHours || 0; return { labels: months.map((x) => MON[+x.slice(5, 7) - 1]), lines: [{ name: "Approved hours", values: months.map((x) => Math.round(m[x])) }] }; }, fmt: (v) => `${v} h` },
};
const xmSeriesFor = (kind) => Object.entries(XM_SERIES).filter(([, s]) => s.kind === kind).map(([k, s]) => [k, s.name]);

/* ---- the component catalog ---- */
const XM_CATS = ["Information", "Data", "KPI", "Actions", "Time", "Finance", "HR", "Payroll", "Analytics", "Navigation"];
const XM_OPT_DEFS = {
  title: { label: "Display title", type: "text" }, description: { label: "Description", type: "text" }, text: { label: "Text (plain text only)", type: "textarea" },
  scope: { label: "Data scope", type: "select", opts: XM_SCOPES }, range: { label: "Date range", type: "select", opts: XM_RANGES }, density: { label: "Display density", type: "select", opts: [["standard", "Standard"], ["compact", "Compact"], ["detailed", "Detailed"]] },
  limit: { label: "Rows to show", type: "select", opts: [["5", "5"], ["8", "8"], ["10", "10"], ["15", "15"], ["25", "25"]] }, days: { label: "Days ahead", type: "select", opts: [["14", "14 days"], ["30", "30 days"], ["60", "60 days"], ["90", "90 days"]] },
  dataset: { label: "Data source", type: "select", opts: () => Object.entries(XM_DATASETS).map(([k, d]) => [k, d.name]) }, columns: { label: "Columns", type: "multi", opts: (c) => (XM_DATASETS[c.dataset]?.cols || []).map(([k, l]) => [k, l]) }, sort: { label: "Sort by", type: "select", opts: (c) => [["date-desc", "Newest first"], ["date-asc", "Oldest first"], ...(XM_DATASETS[c.dataset]?.cols || []).map(([k, l]) => [k, l])] },
  metrics: { label: "Figures", type: "multi", opts: () => Object.entries(XM_METRICS).map(([k, m]) => [k, m.name]) }, metric: { label: "Figure", type: "select", opts: () => Object.entries(XM_METRICS).map(([k, m]) => [k, m.name]) },
  series: { label: "Dataset", type: "select", opts: () => xmSeriesFor("cat") }, tseries: { label: "Dataset", type: "select", opts: () => xmSeriesFor("time") },
  actions: { label: "Actions", type: "multi", opts: () => XM_ACTIONS_LIB.map((a) => [a.id, a.label]) }, action: { label: "Action", type: "select", opts: () => XM_ACTIONS_LIB.map((a) => [a.id, a.label]) },
  pages: { label: "Pages", type: "multi", opts: () => xmPageRegistry().map((p) => [p.key, p.name]) }, q: { label: "Search for", type: "text" },
  goal: { label: "Goal", type: "select", opts: [["timesheets-submitted", "Timesheets submitted this period"], ["certs-valid", "Certificates in date"], ["onboarding-done", "Onboarding tasks done"], ["tasks-done", "Team tasks completed"], ["bills-matched", "Bills matched to a PO"]] },
};
const xmDef = (name, cat, purpose, data, perm, opts, defaults, render, type = "system") => ({ name, cat, purpose, data, perm, opts, defaults, render, type });
function xmTableHtml(c, limitDefault = 8) {
  const ds = XM_DATASETS[c.dataset]; if (!ds) return xmEmptyMsg("Choose a data source.");
  if (!xmAllowed(ds.perm)) return "";
  let rows = []; try { rows = ds.rows(c) || []; } catch (e) { console.error(e); rows = []; }
  const cols = (c.columns && c.columns.length ? ds.cols.filter(([k]) => c.columns.includes(k)) : ds.cols);
  const sort = c.sort || "date-desc";
  rows.sort((a, b) => { if (sort === "date-desc" || sort === "date-asc") { const x = String(a.date ?? ""), y = String(b.date ?? ""); return sort === "date-desc" ? (x < y ? 1 : x > y ? -1 : 0) : (x < y ? -1 : x > y ? 1 : 0); } const x = a[sort], y = b[sort]; return typeof x === "number" && typeof y === "number" ? y - x : String(x ?? "").localeCompare(String(y ?? "")); });
  const n = +c.limit || limitDefault, shown = rows.slice(0, n);
  const cell = (r, [k, , kind]) => { const v = r[k]; if (kind === "money") return td(v == null ? "—" : money(v), 1); if (kind === "hours") return td(hrs(v), 1); if (kind === "num") return td(v ?? "—", 1); if (kind === "pct") return td(`${v}%`, 1); if (kind === "date") return td(v ? dShort(v) : "—"); if (kind === "datetime") return td(v ? dTime(v) : "—"); if (kind === "badge") return td(badge(v)); return td(esc(v ?? "")); };
  return { rows, shown, html: table(cols.map(([k, l, kind]) => (["money", "hours", "num", "pct"].includes(kind) ? ">" + l : l)), shown.map((r) => `<tr ${r.go ? `class="click" data-go="${esc(r.go)}"` : ""}>${cols.map((col) => cell(r, col)).join("")}</tr>`), "Nothing to show."), cols };
}
function xmDatasetListHtml(c, limitDefault = 6) {
  const t = xmTableHtml(c, limitDefault); if (typeof t !== "object") return t;
  const ds = XM_DATASETS[c.dataset];
  const [k1, k2] = ds.cols; const money$ = ds.cols.find((x) => x[2] === "money"), badge$ = ds.cols.find((x) => x[2] === "badge");
  return `<ul class="xm-list">${t.shown.map((r) => `<li ${r.go ? `data-go="${esc(r.go)}" style="cursor:pointer"` : ""}><span style="min-width:0"><b>${esc(r[k1[0]] ?? "")}</b>${k2 ? `<small>${esc(r[k2[0]] ?? "")}${badge$ ? ` · ${xmStatusWord(r[badge$[0]])}` : ""}</small>` : ""}</span>${money$ ? `<span class="num">${money(r[money$[0]])}</span>` : r.date ? `<span class="hint">${esc(dShort(String(r.date).slice(0, 10)))}</span>` : ""}</li>`).join("") || `<li class="xm-empty">Nothing to show.</li>`}</ul>`;
}
const xmDsLink = (c) => { const ds = XM_DATASETS[c.dataset]; return ds?.link && xmAllowed(ds.perm) ? xmLink(ds.link[0], ds.link[1]) : ""; };
const XM_COMPONENTS = {
  /* Information */
  "summary": xmDef("Summary", "Information", "A short paragraph of plain text for the top of a page — a welcome, a note from management, a reminder.", "Text you enter", null, ["title", "text", "size"], { title: "Summary", text: "" }, (c) => xmCard(c.title, `<div class="xm-note">${esc(c.text || "Add the text in the component settings.")}</div>`), "configurable"),
  "text": xmDef("Text", "Information", "Free text (plain text only, no links or formatting).", "Text you enter", null, ["title", "text", "size"], { title: "", text: "" }, (c) => xmCard(c.title, `<div class="xm-note">${esc(c.text || "Add the text in the component settings.")}</div>`), "configurable"),
  "announcement": xmDef("Announcement", "Information", "A highlighted message everyone should notice.", "Text you enter", null, ["title", "text", "size"], { title: "Announcement", text: "" }, (c) => `<div class="xm-ann"><div class="xm-note"><b>${esc(c.title || "Announcement")}</b><br>${esc(c.text || "Add the text in the component settings.")}</div></div>`, "configurable"),
  "employee-info": xmDef("Employee Information", "Information", "The signed-in person's own record: number, company, department, position, manager, start date, status.", "Employee record (own)", "@employee", ["title", "size"], { title: "Employee information" }, (c) => { const e = A.employee; return xmCard(c.title, `<dl class="xm-kv"><dt>Name</dt><dd>${esc(empName(e))}</dd><dt>Employee number</dt><dd class="mono">${esc(e.employeeNumber)}</dd><dt>Company</dt><dd>${coTag(e.companyId)}</dd><dt>Department</dt><dd>${esc(byId(S.departments, e.departmentId)?.name || "—")}</dd><dt>Position</dt><dd>${esc(byId(S.positions, e.positionId)?.title || "—")}</dd><dt>Manager</dt><dd>${esc(e.managerId ? empName(byId(S.employees, e.managerId)) : "—")}</dd><dt>Start date</dt><dd>${esc(dLong(e.startDate))}</dd><dt>Status</dt><dd>${badge(e.status)}</dd></dl>`, xmLink("/me/profile", "My profile →")); }),
  "status": xmDef("Status", "Information", "Where the person's own open requests, claims and time off stand.", "Requests, claims and time off (own)", "@employee", ["title", "limit", "size"], { title: "My open items", limit: "5" }, (c) => { const OPEN = ["PENDING_APPROVAL", "SUBMITTED", "OPEN"]; const rows = statusRows(A.employee.id).filter((r) => OPEN.includes(r.status)).slice(0, +c.limit || 5); return xmCard(c.title, rows.length ? xmList(rows.map((r) => ({ t: `${r.kind} · ${r.title}`, s: r.waiting ? `Waiting on ${r.waiting}` : xmStatusWord(r.status), r: r.amount != null ? money(r.amount) : null }))) : xmEmptyMsg("Nothing waiting on a decision."), xmLink("/me/requests", "All of them →")); }),
  "activity-feed": xmDef("Activity Feed", "Information", "What has happened recently — for the person, their team or everything they may see.", "Audit history", null, ["title", "scope", "limit", "size"], { title: "Activity", scope: "user", limit: "8" }, (c) => xmCard(c.title, xmDatasetListHtml({ ...c, dataset: "recent-activity" }, +c.limit || 8), xmLink("/history", "All history →"))),
  /* Data */
  "data-table": xmDef("Data Table", "Data", "A table from an approved data source with the columns, sort order and page size you choose.", "Approved ERP datasets", null, ["title", "dataset", "columns", "sort", "limit", "scope", "range", "density", "size"], { title: "", dataset: "pending-approvals", limit: "8", scope: "organization", range: "all", size: "large" }, (c) => { const t = xmTableHtml(c); if (typeof t !== "object") return t; const ds = XM_DATASETS[c.dataset]; return xmCard(c.title || ds.name, `<div class="${c.density === "compact" ? "xm-compact" : ""}">${t.html}</div>`, xmDsLink(c)); }, "configurable"),
  "data-list": xmDef("Data List", "Data", "A compact list from an approved data source.", "Approved ERP datasets", null, ["title", "dataset", "limit", "scope", "range", "size"], { title: "", dataset: "my-requests", limit: "6", scope: "user", range: "all" }, (c) => { const ds = XM_DATASETS[c.dataset]; if (!ds || !xmAllowed(ds.perm)) return ""; return xmCard(c.title || ds.name, xmDatasetListHtml(c), xmDsLink(c)); }, "configurable"),
  "record-list": xmDef("Record List", "Data", "Records that open on click — bills, invoices, employees, tasks, projects.", "Approved ERP datasets", null, ["title", "dataset", "limit", "scope", "size"], { title: "", dataset: "open-bills", limit: "8", scope: "organization" }, (c) => { const ds = XM_DATASETS[c.dataset]; if (!ds || !xmAllowed(ds.perm)) return ""; return xmCard(c.title || ds.name, xmDatasetListHtml(c), xmDsLink(c)); }, "configurable"),
  "recent-activity": xmDef("Recent Activity", "Data", "The latest changes, newest first.", "Audit history", null, ["title", "scope", "limit", "size"], { title: "Recent activity", scope: "team", limit: "6" }, (c) => xmCard(c.title, xmDatasetListHtml({ ...c, dataset: "recent-activity" }, +c.limit || 6), xmLink("/history", "All history →"))),
  "search-results": xmDef("Search Results", "Data", "A saved search, shown as a list — the same search as the top bar, limited to what this person may open.", "Global search", null, ["title", "q", "limit", "size"], { title: "Search", q: "", limit: "8" }, (c) => { if (!c.q) return xmCard(c.title, xmEmptyMsg("Enter a search term in the component settings.")); const groups = searchResults(c.q); const items = groups.flatMap(([g, list]) => list.map((x) => ({ ...x, g }))).slice(0, +c.limit || 8); return xmCard(`${c.title || "Search"} · “${c.q}”`, items.length ? `<ul class="xm-list">${items.map((x) => `<li data-go="${esc(x.go)}" style="cursor:pointer"><span><b>${esc(x.t)}</b><small>${esc(x.g)} · ${esc(x.s || "")}</small></span></li>`).join("")}</ul>` : xmEmptyMsg(`Nothing found for “${c.q}”.`)); }, "configurable"),
  /* KPI */
  "kpi-card": xmDef("KPI Card", "KPI", "Up to four figures side by side, each from ERP data and each opening its page.", "Approved metrics", null, ["title", "metrics", "size"], { title: "", metrics: ["pending-approvals", "employees"], size: "large" }, (c) => { const tiles = (c.metrics || []).map((k) => XM_METRICS[k]).filter((m) => m && xmAllowed(m.perm)).slice(0, 4).map((m) => { try { const v = m.value(); return { l: m.name, ...v }; } catch (e) { console.error(e); return null; } }).filter(Boolean); return tiles.length ? xmCard(c.title, xmTiles(tiles)) : ""; }, "configurable"),
  "metric": xmDef("Metric", "KPI", "One figure, large, with its explanation.", "Approved metrics", null, ["title", "metric", "size"], { title: "", metric: "pending-approvals", size: "small" }, (c) => { const m = XM_METRICS[c.metric]; if (!m || !xmAllowed(m.perm)) return ""; const v = m.value(); return xmTiles([{ l: c.title || m.name, ...v }]); }, "configurable"),
  "progress": xmDef("Progress Indicator", "KPI", "How far along a goal is, as a bar: timesheets in, certificates in date, onboarding done, tasks done, bills matched.", "Approved goals", null, ["title", "goal", "scope", "size"], { title: "", goal: "timesheets-submitted", scope: "organization" }, (c) => xmGoalHtml(c, false), "configurable"),
  "goal": xmDef("Goal / Target", "KPI", "A goal with its target and the number achieved so far.", "Approved goals", null, ["title", "goal", "scope", "size"], { title: "", goal: "certs-valid", scope: "organization" }, (c) => xmGoalHtml(c, true), "configurable"),
  /* Actions */
  "quick-actions": xmDef("Quick Actions", "Actions", "Buttons that open existing workflows — enter time, request time off, enter a bill. Only the ones this person may use are shown.", "Approved actions", null, ["title", "actions", "size"], { title: "Quick actions", actions: ["enter-time", "request-time-off", "submit-expense", "new-request"] }, (c) => { const list = (c.actions || []).map((id) => XM_ACTION_BY_ID[id]).filter((x) => x && xmAllowed(x.perm)).slice(0, 8); return list.length ? xmCard(c.title, `<div class="qa2">${list.map(xmActionBtn).join("")}</div>`) : ""; }, "configurable"),
  "action-button": xmDef("Action Button", "Actions", "One prominent button that opens an existing workflow.", "Approved actions", null, ["title", "action", "size"], { title: "", action: "request-time-off", size: "small" }, (c) => { const x = XM_ACTION_BY_ID[c.action]; if (!x || !xmAllowed(x.perm)) return ""; return `<section class="hcard" style="padding:12px"><button class="btn pri" style="width:100%;justify-content:center;gap:8px" ${x.act ? `data-a="${esc(x.act)}"` : `data-go="${esc(x.go)}"`}>${icon(x.icon)} ${esc(c.title || x.label)}</button></section>`; }, "configurable"),
  "request-shortcut": xmDef("Request Shortcut", "Actions", "Start a new request of each kind: time off, expense, travel, credit card, purchase.", "Request centre", "@employee", ["title", "size"], { title: "New request" }, (c) => xmCard(c.title, `<div class="qa2">${[["/me/time-off", "calendar", "Time off"], ["/me/expenses", "receipt", "Expense claim"], ["/me/requests/new/TRAVEL_REQUEST", "map", "Travel request"], ["/me/requests/new/CREDIT_CARD_PURCHASE", "wallet", "Credit card purchase"], ["/me/requests/new/TRAVEL_CLAIM", "receipt", "Travel claim"], ["/me/requests", "cart", "Purchase request"]].map(([go, ic, l]) => `<button data-go="${go}">${icon(ic)}<span>${esc(l)}</span></button>`).join("")}</div>`)),
  "approval-action": xmDef("Approval Action", "Actions", "What is waiting for this person's decision, with Approve / Decline right there (the platform's own approval cards).", "Approvals", null, ["title", "size"], { title: "Waiting on you", size: "large" }, (c) => { if (!(myActionable().length || myTimesheetsToApprove().length)) return xmCard(c.title, xmEmptyMsg("All caught up — nothing waiting for your decision."), xmLink("/approvals", "Approvals →")); return `<div class="xm-wrapblock">${waitingOnYou(UI.route.split("?")[0])}</div>`; }),
  /* Time */
  "calendar": xmDef("Calendar", "Time", "What is coming up: time off, stat holidays, pay days, review and certificate dates.", "Events", null, ["title", "days", "limit", "size"], { title: "Coming up", days: "60", limit: "6" }, (c) => { const ev = upcomingEventsA(+c.days || 60).slice(0, +c.limit || 6); return xmCard(c.title, ev.length ? `<ul class="hlist">${ev.map((x) => `<li class="erow"><span class="dt">${esc(dShort(x.at))}</span><span class="dot" style="background:${EVENT_K[x.k]?.[1] || "var(--c1)"}" aria-hidden="true"></span><span class="tx"><b>${esc(x.t)}</b></span></li>`).join("")}</ul>` : xmEmptyMsg("Nothing in the next few weeks."), A.employee ? xmLink("/me/profile/events", "Calendar →") : ""); }),
  "timesheet-summary": xmDef("Timesheet Summary", "Time", "The current pay period: hours entered, status, days left — or, for a team, who has sent theirs in.", "Timesheets", "@employee", ["title", "scope", "size"], { title: "This pay period", scope: "user" }, (c) => { const e = A.employee, p = xmCurrentPeriod(e); if (c.scope === "user") { const s = S.timesheets.find((t) => t.employeeId === e.id && t.periodStart === p.start); const left = Math.max(0, Math.round((D(p.end) - D(todayStr())) / MS_DAY)); return xmCard(c.title, xmTiles([{ l: "Period", v: periodLabel(p.start, p.end).replace(/, \d{4}$/, ""), h: `${left} day${left === 1 ? "" : "s"} left` }, { l: "Hours entered", v: s ? hrs(s.workedHours) : "0.00", h: s ? xmStatusWord(s.status) : "Not started", go: "/me/time" }]), xmLink("/me/time", "My Time →")); } const emps = xmScopeEmps(c.scope).filter((x) => x.id !== e.id || c.scope !== "team"); const sent = emps.filter((x) => S.timesheets.some((t) => t.employeeId === x.id && t.periodStart === p.start && ["SUBMITTED", "APPROVED", "LOCKED"].includes(t.status))).length; return xmCard(c.title, xmTiles([{ l: "People", v: String(emps.length), h: xmScopeText(c.scope) }, { l: "Timesheets in", v: `${sent} / ${emps.length}`, h: periodLabel(p.start, p.end), go: can(A, "timesheets.view") ? "/hr/timesheets" : "/team" }]), can(A, "timesheets.view") ? xmLink("/hr/timesheets", "Timesheets →") : ""); }),
  "leave-balance": xmDef("Leave Balance", "Time", "The person's available leave by type, with Request time off.", "Leave balance records (own)", "@employee", ["title", "size"], { title: "Leave balance" }, (c) => { const b = leaveBalances(A.employee.id).filter((x) => x.has); return xmCard(c.title, (b.length ? `<ul class="xm-list">${b.map((x) => `<li><span><b>${esc(x.lt.name)}</b><small>${hrs(x.used)} h used${x.pending ? ` · ${hrs(x.pending)} h waiting` : ""}</small></span><span class="num">${hrs(x.avail)} h</span></li>`).join("")}</ul>` : xmEmptyMsg("No balances on file for this year.")) + `<div style="padding:8px 14px 12px"><button class="btn pri sm" data-go="/me/time-off">Request time off</button></div>`); }),
  "upcoming-events": xmDef("Upcoming Events", "Time", "The next events as a simple list.", "Events", null, ["title", "days", "limit", "size"], { title: "Upcoming", days: "30", limit: "5" }, (c) => xmCard(c.title, xmDatasetListHtml({ ...c, dataset: "upcoming-events" }, +c.limit || 5))),
  /* Finance */
  "invoice-summary": xmDef("Invoice Summary", "Finance", "Customer invoices by status and what is still owed.", "Accounts receivable", "ar.view", ["title", "size"], { title: "Customer invoices" }, (c) => { const l = inScope(S.arInvoices); const open = xmOpenInvoices(); const t = todayStr(); return xmCard(c.title, xmTiles([{ l: "Open", v: moneyCompact(xmNetOpen(open)), h: `${open.length} invoice${open.length === 1 ? "" : "s"}`, go: "/finance/ar" }, { l: "Overdue", v: moneyCompact(xmNetOpen(open.filter((i) => i.dueDate < t))), h: "Past due", go: "/finance/ar" }, { l: "Paid this year", v: moneyCompact(l.filter((i) => i.status === "PAID").reduce((s, i) => s + (i.paidCents || i.totalCents || 0), 0)), h: "Settled" }]), xmLink("/finance/ar", "Invoices →")); }),
  "ap-aging": xmDef("AP Aging", "Finance", "What is owed to vendors, by how overdue it is.", "Accounts payable", "ap.view", ["title", "size"], { title: "AP aging" }, (c) => xmCard(c.title, xmBars(xmAging(xmOpenBills())), xmLink("/finance/ap", "Bills →"))),
  "ar-aging": xmDef("AR Aging", "Finance", "What customers owe, by how overdue it is.", "Accounts receivable", "ar.view", ["title", "size"], { title: "AR aging" }, (c) => xmCard(c.title, xmBars(xmAging(xmOpenInvoices())), xmLink("/finance/ar", "Invoices →"))),
  "expense-summary": xmDef("Expense Summary", "Finance", "Expense claims in the period: open, approved, paid back — for the person, a team or the company.", "Expense claims", ["expenses.view", "@employee"], ["title", "scope", "range", "size"], { title: "Expenses", scope: "user", range: "quarter" }, (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); const r = xmRangeDates(c.range); const l = inScope(S.expenseClaims).filter((x) => emps.has(x.employeeId) && (can(A, "expenses.view") || x.employeeId === A.employee?.id) && (c.range === "all" || xmInRange(x.createdAt, r))); const sum = (f) => l.filter(f).reduce((s, x) => s + (x.totalCents || 0), 0); return xmCard(c.title, xmTiles([{ l: "Claims", v: String(l.length), h: XM_RANGES.find((x) => x[0] === c.range)?.[1] || "" }, { l: "Waiting", v: moneyCompact(sum((x) => ["SUBMITTED", "PENDING_APPROVAL"].includes(x.status))), h: "For approval" }, { l: "Paid back", v: moneyCompact(sum((x) => x.status === "PAID" || x.status === "REIMBURSED")), h: "Reimbursed" }]), xmLink(can(A, "expenses.view") ? "/finance/expenses" : "/me/expenses", "Claims →")); }),
  "budget-summary": xmDef("Budget Summary", "Finance", "Budget versus posted spend for the fiscal year, by account.", "Budgets and the ledger", "budgets.view", ["title", "limit", "size"], { title: "Budget vs actual", limit: "8" }, (c) => { const ids = scopeIds(S, A); const yr = todayStr().slice(0, 4); const budgets = S.budgets.filter((b) => ids.includes(b.companyId) && String(b.fiscalYear) === yr); if (!budgets.length) return xmCard(c.title, xmEmptyMsg(`No budget for ${yr} in this scope.`), xmLink("/finance/budgets", "Budgets →")); const bl = new Map(); for (const l of S.budgetLines) if (budgets.some((b) => b.id === l.budgetId)) bl.set(l.accountId, (bl.get(l.accountId) || 0) + (l.amountCents || 0)); const actual = new Map(); const je = new Map(S.journalEntries.filter((j) => ids.includes(j.companyId) && j.date.startsWith(yr) && j.status !== "VOID").map((j) => [j.id, j])); for (const l of S.journalLines) if (je.has(l.journalEntryId) && bl.has(l.accountId)) actual.set(l.accountId, (actual.get(l.accountId) || 0) + (l.debitCents || 0) - (l.creditCents || 0)); const rows = [...bl].map(([acc, b]) => ({ name: xmAcct(acc)?.name || acc, b, a: actual.get(acc) || 0 })).sort((x, y) => y.b - x.b).slice(0, +c.limit || 8); return xmCard(c.title, `<div class="xm-bars">${rows.map((r) => `<div class="hbar"><span class="nm" title="${esc(r.name)}">${esc(r.name)}</span><span class="tr"><i style="width:${Math.min(100, Math.round((r.a / Math.max(1, r.b)) * 100))}%;background:${r.a > r.b ? "var(--bad)" : "var(--action)"}"></i></span><span class="num" style="font-size:12px;white-space:nowrap">${moneyCompact(r.a)} / ${moneyCompact(r.b)}</span></div>`).join("")}</div>`, xmLink("/finance/budgets", "Budgets →")); }),
  "payment-status": xmDef("Payment Status", "Finance", "Bills approved and waiting to be paid, paid this month, and deposits received.", "Payables and receivables", "ap.view", ["title", "size"], { title: "Payments" }, (c) => { const m = todayStr().slice(0, 7); const toPay = xmOpenBills().filter((i) => ["APPROVED", "PARTIALLY_PAID"].includes(i.status)); const paid = inScope(S.apInvoices).filter((i) => i.status === "PAID" && (i.paidAt || i.postedAt || "").startsWith(m)); const dep = can(A, "ar.view") ? inScope(S.arInvoices).filter((i) => i.status === "PAID" && (i.paidAt || i.postedAt || "").startsWith(m)) : []; return xmCard(c.title, xmTiles([{ l: "Ready to pay", v: moneyCompact(xmNetOpen(toPay)), h: `${toPay.length} approved bill${toPay.length === 1 ? "" : "s"}`, go: "/finance/ap/pay" }, { l: "Paid this month", v: moneyCompact(paid.reduce((s, i) => s + (i.totalCents || 0), 0)), h: `${paid.length} bill${paid.length === 1 ? "" : "s"}` }, ...(can(A, "ar.view") ? [{ l: "Received this month", v: moneyCompact(dep.reduce((s, i) => s + (i.totalCents || 0), 0)), h: `${dep.length} invoice${dep.length === 1 ? "" : "s"}`, go: "/finance/ar" }] : [])]), xmLink("/finance/ap", "Bills →")); }),
  /* HR */
  "headcount": xmDef("Headcount", "HR", "People by company or department.", "Employee records", ["hr.employees.view", "@employee"], ["title", "series", "size"], { title: "Headcount", series: "headcount-department" }, (c) => { const s = XM_SERIES[c.series] || XM_SERIES["headcount-department"]; return xmCard(c.title, xmBars(s.items(c)), xmLink(can(A, "hr.employees.view") ? "/hr/employees" : "/people/directory", "People →")); }, "configurable"),
  "employee-status": xmDef("Employee Status", "HR", "How many people are active, on leave, starting or have left.", "Employee records", "hr.employees.view", ["title", "scope", "size"], { title: "Employee status", scope: "organization" }, (c) => { const ids = scopeIds(S, A); const l = S.employees.filter((e) => ids.includes(e.companyId)); const n = (s) => l.filter((e) => e.status === s).length; return xmCard(c.title, xmTiles([{ l: "Active", v: String(n("ACTIVE")), go: "/hr/employees" }, { l: "On leave", v: String(n("ON_LEAVE")), go: "/hr/employees" }, { l: "Starting", v: String(n("ONBOARDING")), h: "In onboarding", go: "/hr/onboarding" }, { l: "Left", v: String(n("TERMINATED")), h: "This year" }]), xmLink("/hr/employees", "Employee records →")); }),
  "leave-summary": xmDef("Leave Summary", "HR", "Time off waiting, approved and who is away this month.", "Time-off requests", ["leave.view", "@employee"], ["title", "scope", "size"], { title: "Time off", scope: "organization" }, (c) => { const emps = new Set(xmScopeEmps(c.scope).map((e) => e.id)); const l = S.leaveRequests.filter((r) => emps.has(r.employeeId) && (can(A, "leave.view") || r.employeeId === A.employee?.id)); const m = todayStr().slice(0, 7); const away = l.filter((r) => r.status === "APPROVED" && r.startDate.slice(0, 7) <= m && r.endDate.slice(0, 7) >= m); return xmCard(c.title, xmTiles([{ l: "Waiting", v: String(l.filter((r) => r.status === "PENDING_APPROVAL").length), h: "Not yet decided", go: can(A, "leave.view") ? "/hr/leave" : "/me/time-off" }, { l: "Away this month", v: String(new Set(away.map((r) => r.employeeId)).size), h: `${hrs(away.reduce((s, r) => s + (r.totalHours || 0), 0))} h approved` }]) + (away.length ? xmList(away.slice(0, 5).map((r) => ({ t: empName(byId(S.employees, r.employeeId)), s: `${byId(S.leaveTypes, r.leaveTypeId)?.name || ""} · ${dShort(r.startDate)}${r.endDate !== r.startDate ? " → " + dShort(r.endDate) : ""}` }))) : ""), xmLink(can(A, "leave.view") ? "/hr/leave" : "/me/time-off", "Time off →")); }),
  "employee-documents": xmDef("Employee Documents", "HR", "Policies, templates and the documents this person may open.", "Document library", ["documents.view", "@employee"], ["title", "limit", "size"], { title: "Documents", limit: "6" }, (c) => xmCard(c.title, xmDatasetListHtml({ ...c, dataset: "documents" }, +c.limit || 6), xmLink(can(A, "documents.view") ? "/documents" : "/me/documents", "Documents →"))),
  "birthdays": xmDef("Birthday / Anniversary", "HR", "Work anniversaries coming up (the platform keeps start dates, not birthdays).", "Employee records", ["hr.employees.view", "@employee"], ["title", "days", "scope", "size"], { title: "Work anniversaries", days: "60", scope: "company" }, (c) => { const t = todayStr(), yr = +t.slice(0, 4); const rows = xmScopeEmps(c.scope).map((e) => { if (!e.startDate) return null; const md = e.startDate.slice(5); let next = `${yr}-${md}`; if (next < t) next = `${yr + 1}-${md}`; const days = Math.round((D(next) - D(t)) / MS_DAY); const years = +next.slice(0, 4) - +e.startDate.slice(0, 4); return years > 0 && days <= (+c.days || 60) ? { t: empName(e), s: `${years} year${years === 1 ? "" : "s"} on ${dShort(next)}`, r: days === 0 ? "Today" : `in ${days} d`, days } : null; }).filter(Boolean).sort((a, b) => a.days - b.days); return xmCard(c.title, rows.length ? xmList(rows.slice(0, 8)) : xmEmptyMsg("No anniversaries in this window.")); }),
  /* Payroll */
  "payroll-summary": xmDef("Payroll Summary", "Payroll", "The last posted pay run: gross, deductions, employer costs, net, and the next pay day.", "Payroll runs", "payroll.view", ["title", "size"], { title: "Payroll" }, (c) => { const runs = inScope(S.payrollRuns).sort((a, b) => (a.payDate < b.payDate ? 1 : -1)); const last = runs.find((r) => r.status === "POSTED"); const next = runs.find((r) => r.status !== "POSTED" && r.payDate >= todayStr()); return xmCard(c.title, last ? xmTiles([{ l: "Gross", v: moneyCompact(last.grossCents), h: `${last.employeeCount} people · ${dLong(last.payDate)}`, go: `/payroll/runs/${last.id}` }, { l: "Deductions", v: moneyCompact(last.employeeDeductionsCents || 0), h: "Employee" }, { l: "Employer costs", v: moneyCompact(last.employerCostsCents || 0), h: "CPP, EI" }, { l: "Net pay", v: moneyCompact(last.netCents), h: next ? `Next run ${dLong(next.payDate)}` : "No run open" }]) : xmEmptyMsg("No pay run posted yet."), xmLink("/payroll/runs", "Pay runs →")); }),
  "pay-period": xmDef("Pay Period", "Payroll", "The current pay period, when it ends and when timesheets are due.", "Payroll settings", "@employee", ["title", "size"], { title: "Pay period", size: "small" }, (c) => { const e = A.employee, p = xmCurrentPeriod(e); const left = Math.max(0, Math.round((D(p.end) - D(todayStr())) / MS_DAY)); return xmCard(c.title, `<dl class="xm-kv"><dt>Period</dt><dd>${esc(periodLabel(p.start, p.end))}</dd><dt>Cadence</dt><dd>${p.cad === "WEEKLY" ? "Weekly" : "Every two weeks"}</dd><dt>Timesheet due</dt><dd>${esc(dLong(p.end))} · ${left} day${left === 1 ? "" : "s"} left</dd></dl>`, xmLink("/me/time", "My Time →")); }),
  "payroll-status": xmDef("Payroll Status", "Payroll", "Pay runs by stage: open, calculated, waiting for approval, posted.", "Payroll runs", "payroll.view", ["title", "size"], { title: "Pay runs by status" }, (c) => xmCard(c.title, xmBars(groupBars(inScope(S.payrollRuns), (r) => xmStatusWord(r.status), () => 1, (v) => String(v))), xmLink("/payroll/runs", "Pay runs →"))),
  "deduction-summary": xmDef("Deduction Summary", "Payroll", "Deductions and employer contributions on the last posted run, by type.", "Payroll lines", "payroll.view", ["title", "size"], { title: "Deductions" }, (c) => { const last = inScope(S.payrollRuns).filter((r) => r.status === "POSTED").sort((a, b) => (a.payDate < b.payDate ? 1 : -1))[0]; if (!last) return xmCard(c.title, xmEmptyMsg("No pay run posted yet.")); const entries = new Set(S.payrollEntries.filter((p) => p.payrollRunId === last.id).map((p) => p.id)); const items = groupBars((S.payrollLines || []).filter((l) => entries.has(l.payrollEntryId) && /DEDUCTION|EMPLOYER|TAX/i.test(l.kind || "")), (l) => l.description || l.typeCode || l.kind, (l) => l.amountCents || 0, moneyCompact); return xmCard(c.title, items.length ? xmBars(items) : xmEmptyMsg("No deduction lines on the last run."), xmLink(`/payroll/runs/${last.id}`, "Open the run →")); }),
  /* Analytics */
  "bar-chart": xmDef("Bar Chart", "Analytics", "Compare amounts across categories from an approved dataset.", "Approved chart datasets", null, ["title", "series", "scope", "range", "size"], { title: "", series: "headcount-department", scope: "organization", range: "year" }, (c) => { const s = XM_SERIES[c.series]; if (!s || !xmAllowed(s.perm)) return ""; return xmCard(c.title || s.name, xmBars(s.items(c))); }, "configurable"),
  "line-chart": xmDef("Line Chart", "Analytics", "A value over time from an approved dataset.", "Approved chart datasets", null, ["title", "tseries", "scope", "size"], { title: "", tseries: "hours-period", scope: "organization", size: "large" }, (c) => { const s = XM_SERIES[c.tseries]; if (!s || !xmAllowed(s.perm)) return ""; const d = s.series(c); return xmCard(c.title || s.name, d.labels.length ? xmLineSvg(d.labels, d.lines, s.fmt) : xmEmptyMsg("Nothing to chart yet.")); }, "configurable"),
  "donut-chart": xmDef("Donut Chart", "Analytics", "Shares of a whole from an approved dataset.", "Approved chart datasets", null, ["title", "series", "scope", "range", "size"], { title: "", series: "bills-status", scope: "organization", range: "year" }, (c) => { const s = XM_SERIES[c.series]; if (!s || !xmAllowed(s.perm)) return ""; const items = foldSlices(s.items(c)); return xmCard(c.title || s.name, items.length ? `<div style="padding:10px 12px">${donut(items, { title: "", caption: "total", size: 130, thick: 16 })}</div>` : xmEmptyMsg("Nothing to chart yet.")); }, "configurable"),
  "trend-chart": xmDef("Trend Chart", "Analytics", "A line over time with the change from the previous point.", "Approved chart datasets", null, ["title", "tseries", "scope", "size"], { title: "", tseries: "revenue-expenses", scope: "organization", size: "large" }, (c) => { const s = XM_SERIES[c.tseries]; if (!s || !xmAllowed(s.perm)) return ""; const d = s.series(c); const l0 = d.lines[0]; const last = l0?.values.at(-1) ?? 0, prev = l0?.values.at(-2) ?? 0; const delta = prev ? Math.round(((last - prev) / Math.abs(prev)) * 100) : null; return xmCard(c.title || s.name, (d.labels.length ? xmLineSvg(d.labels, d.lines, s.fmt) : xmEmptyMsg("Nothing to chart yet.")), delta != null ? `<span class="badge ${delta >= 0 ? "tone-green" : "tone-red"}">${delta >= 0 ? "▲" : "▼"} ${Math.abs(delta)}% vs previous</span>` : ""); }, "configurable"),
  /* Navigation */
  "quick-links": xmDef("Quick Links", "Navigation", "Links to the pages you choose; only pages this person may open are shown.", "Page registry", null, ["title", "pages", "size"], { title: "Quick links", pages: ["/me/time", "/me/time-off", "/me/pay", "/me/documents"] }, (c) => { const list = (c.pages || []).map((k) => ({ k, p: xmPageDef(k) })).filter(({ k, p }) => p && xmDestAllowed({ dest: k.startsWith("/pages/") ? { type: "page", slug: k.slice(7) } : { type: "route", href: k } })); return list.length ? xmCard(c.title, `<div class="qa2">${list.map(({ k, p }) => `<button data-go="${esc(k)}">${icon("chevright")}<span>${esc(p.name)}</span></button>`).join("")}</div>`) : ""; }, "configurable"),
  "related-pages": xmDef("Related Pages", "Navigation", "The other pages in this page's section (the same tabs the top bar shows).", "Navigation", null, ["title", "size"], { title: "Related pages" }, (c) => { const path = parseRoute(UI.route).path; const sec = sectionFor(path); if (!sec) return ""; const tabs = visibleTabs(sec).filter((t) => t.href !== path); return tabs.length ? xmCard(c.title, `<div class="qa2">${tabs.map((t) => `<button data-go="${esc(t.href)}" data-sec="${esc(sec.key)}">${icon("chevright")}<span>${esc(t.label)}</span></button>`).join("")}</div>`) : ""; }),
  "module-shortcuts": xmDef("Module Shortcuts", "Navigation", "One button per area of the platform this person can open — the sidebar, as tiles.", "Navigation", null, ["title", "size"], { title: "Go to", size: "large" }, (c) => { const items = buildNav().flatMap((g) => g.items).filter((i) => i.href !== "/dashboard"); return items.length ? xmCard(c.title, `<div class="qa2" style="grid-template-columns:repeat(auto-fill,minmax(150px,1fr))">${items.map((i) => `<button data-go="${esc(i.href)}" data-sec="${esc(i.section || "")}">${icon(i.icon)}<span>${esc(i.title)}</span></button>`).join("")}</div>`) : ""; }),
};
function xmGoalHtml(c, withTarget) {
  const ids = scopeIds(S, A); let done = 0, total = 0, unit = "", name = XM_OPT_DEFS.goal.opts.find((o) => o[0] === c.goal)?.[1] || "Goal", go = "";
  const emps = xmScopeEmps(c.scope === "user" ? "organization" : c.scope);
  if (c.goal === "timesheets-submitted") { if (!can(A, "timesheets.view") && !teamLeads()) return ""; const t0 = todayStr(); for (const e of emps) { const p = xmCurrentPeriod(e); total++; if (S.timesheets.some((t) => t.employeeId === e.id && t.periodStart === p.start && ["SUBMITTED", "APPROVED", "LOCKED"].includes(t.status))) done++; } unit = "people"; go = can(A, "timesheets.view") ? "/hr/timesheets" : "/team"; void t0; }
  else if (c.goal === "certs-valid") { if (!can(A, "hr.employees.view") && !A.employee) return ""; const set = new Set(emps.map((e) => e.id)); const t = todayStr(); const l = (S.certifications || []).filter((x) => set.has(x.employeeId) && (can(A, "hr.employees.view") || x.employeeId === A.employee?.id)); total = l.length; done = l.filter((x) => !x.expiryDate || x.expiryDate >= t).length; unit = "certificates"; go = can(A, "hr.employees.view") ? "/hr/certifications" : "/me/certifications"; }
  else if (c.goal === "onboarding-done") { if (!can(A, "hr.onboarding.manage")) return ""; const set = new Set(emps.map((e) => e.id)); const l = (S.onboardingTasks || []).filter((x) => set.has(x.employeeId)); total = l.length; done = l.filter((x) => x.isDone || x.completedAt || x.status === "DONE").length; unit = "tasks"; go = "/hr/onboarding"; }
  else if (c.goal === "tasks-done") { if (!A.employee) return ""; const set = new Set(emps.map((e) => e.id)); const l = (S.tasks || []).filter((x) => set.has(x.assigneeId) && (x.assigneeId === A.employee.id || teamLeads())); total = l.length; done = l.filter((x) => x.status === "DONE").length; unit = "tasks"; go = teamLeads() ? "/team" : "/me/tasks"; }
  else if (c.goal === "bills-matched") { if (!can(A, "ap.view")) return ""; const l = inScope(S.apInvoices).filter((i) => i.status !== "DRAFT"); total = l.length; done = l.filter((i) => i.purchaseOrderId || i.poNumber || i.matchStatus === "MATCHED").length; unit = "bills"; go = "/procurement/match"; }
  const pct = total ? Math.round((done / total) * 100) : 0;
  return xmCard(c.title || name, `<div class="xm-prog"><div class="form-row" style="justify-content:space-between"><span style="font-weight:600">${withTarget ? `${done} of ${total} ${unit}` : `${pct}%`}</span><span class="hint">${withTarget ? `target ${total} · ${pct}%` : `${done} of ${total} ${unit}`}</span></div><div class="tr"><i style="width:${pct}%"></i></div><div class="hint">${esc(xmScopeText(c.scope))}</div></div>`, go ? xmLink(go, "Open →") : "");
}
/** the settings a component accepts, with defaults and approved values only */
function xmCompConfig(id, raw) {
  const def = XM_COMPONENTS[id]; if (!def) return {};
  const r = xmIsObj(raw) ? raw : {}; const out = {};
  for (const k of def.opts) {
    const o = XM_OPT_DEFS[k]; const d = def.defaults[k];
    let v = r[k] ?? d;
    if (k === "size") continue;
    if (o.type === "text") v = xmPlain(v, k === "q" ? 60 : 80);
    else if (o.type === "textarea") v = String(v ?? "").replace(/[<>]/g, "").slice(0, 600);
    else if (o.type === "select") { const opts = typeof o.opts === "function" ? o.opts({ ...out, ...r }) : o.opts; v = opts.some((x) => x[0] === String(v)) ? String(v) : opts.some((x) => x[0] === d) ? d : opts[0]?.[0]; }
    else if (o.type === "multi") { const opts = typeof o.opts === "function" ? o.opts({ ...out, ...r }) : o.opts; v = (Array.isArray(v) ? v : typeof v === "string" ? v.split(",") : []).map(String).filter((x) => opts.some((y) => y[0] === x)).slice(0, 12); }
    out[k] = v;
  }
  return out;
}
/** render one configured component for the current person; "" when they may not see it */
function xmRenderComponent(entry) {
  const def = XM_COMPONENTS[entry.component]; if (!def) return "";
  if (!xmAllowed(def.perm)) return "";
  const c = { ...xmCompConfig(entry.component, entry.config), title: entry.title || xmCompConfig(entry.component, entry.config).title, size: entry.size };
  try { return def.render(c) || ""; } catch (e) { console.error(e); return `<div class="xm-unavail">This component couldn't be drawn: ${esc(e.message)}</div>`; }
}
const xmCompSearch = (q) => { const t = String(q || "").trim().toLowerCase(); return Object.entries(XM_COMPONENTS).filter(([id, d]) => !t || id.includes(t) || d.name.toLowerCase().includes(t) || d.cat.toLowerCase().includes(t) || d.purpose.toLowerCase().includes(t) || d.data.toLowerCase().includes(t)); };
